version: '3'

services:

  server:
    image: srd-node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8080:8080"
      - "8081:8081"
    env_file:
      - .env
    environment:
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_INTERVAL: 500
      DEV: 1
    entrypoint: ['yarn' , 'srd:dev']

  build:
    image: srd-node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      DEV: 0
    entrypoint: ['yarn' , 'srd:build']

  u_yarn:
    image: srd-node
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/var/www/html
    env_file:
      - .env
    environment:
      DEV: 0
    entrypoint: ['yarn']